flaskr/models/user.py
from flask import g
from flask.ext.login import UserMixin 
from flask.ext.pymongo import ObjectId

class User(UserMixin):
    _password ='!'

    def __init__(self, user_dict):
        for key, val in user_dict.iteritems():
            setattr(self, key, val)

    def get_id(self):
        return self._id or self.id

    def check_password(self, password):
        if self.password == '!':
            return False
        return self.password == password

    @classmethod
    def find_all(cls):
        users = []
        for user in g.mongo.users.find():
            users.append(cls(user))
        return users

    @classmethod
    def find_one(cls, userid=None, username=None):
        if not id and not username:
            return None
        if userid:
            if type(userid) is not 'bson.objectid.ObjectId':
                userid = ObjectId(userid)
            db_user = g.mongo.users.find({ '_id': userid, })
        elif username:
            db_user = g.mongo.users.find({ 'username': username, })

        if not db_user:
            return None
        return cls(db_user)

flaskr/__init__.py
'''
Flask's flaskr tutorial plus
'''
from contextlib import closing
from flask import Flask, request, session, g, redirect, url_for, abort,\
        render_template, flash, app
from flask.ext.admin import Admin
from flask.ext.login import LoginManager, login_user, logout_user, current_user
from flask.ext.pymongo import PyMongo, ObjectId

from flaskr import config
from flaskr.blueprints.admin import UserView
from flaskr.blueprints.entries import entries
from flaskr.models.user import User

app = Flask(__name__)
app.config.from_object(config)

mongo = PyMongo(app)

login_manager = LoginManager()
login_manager.setup_app(app)

admin = Admin(name='Flaskr')
admin.add_view(UserView(name='Users'))
admin.init_app(app)

@login_manager.user_loader
def load_user(userid):
    db_user = mongo.db.users.find_one({ '_id': ObjectId(str(userid)) })
    user = User(db_user)
    return user

app.register_blueprint(entries)

@app.before_request
def before_request():
    g.mongo = mongo.db

@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        db_user = g.mongo.users.find_one({
            'username': request.form['username'],
            })
        if db_user:
            user = User(db_user)
        else:
            user = None

        if not user:
            error = 'Invalid username'
        elif not user.check_password(request.form['password']):
            error = 'Invalid password'
        else:
            login_user(user)
            flash('You are logged in')
            return redirect(url_for('entries.list'))
    return render_template('login.html', error=error)

@app.route('/logout')
def logout():
    logout_user()
    flash('You are logged out')
    return redirect(url_for('entries.list'))

flaskr/blueprints/admin.py
from flask import Blueprint, request, session, g, redirect, url_for, abort,\
        render_template, flash
from flask.ext.admin import Admin, BaseView, expose
from flask.ext.login import current_user

from flaskr.models.user import User

class UserView(BaseView):
    @expose('/')
    def index(self):
        users =  User.find_all()
        return self.render('admin/users/index.html', users=users)

flaskr/blueprints/entries.py
from flask import Blueprint, request, session, g, redirect, url_for, abort,\
        render_template, flash
from flask.ext.login import current_user

entries = Blueprint('entries', __name__, template_folder='templates')

@entries.route('/')
def list():
    entries = g.mongo.entries.find()
    return render_template('show_entries.html', entries=entries)

@entries.route('/add', methods=['POST'])
def add():
    if not current_user.is_authenticated():
        abort(401)
    g.mongo.entries.save({
        'title': request.form['title'],
        'text': request.form['text'],
        })
    flash('New entry was successfully posted')
    return redirect(url_for('entries.list'))

flaskr/templates/layout.html
<!doctype html>
<html>
  <head>
    <title>Flaskr</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}" />
  </head>
  <body>
    <div class="page">
      <h1>Flaskr</h1>
      <div class="metanav">
        {% if not current_user.is_authenticated() %}
        <a href="{{ url_for('login') }}">log in</a>
        {% else %}
        <a href="{{ url_for('logout') }}">log out</a>
        {% endif %}
      </div>
      {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
      {% endfor %}

      {% block body %}{% endblock %}
    </div>
  </body>
</html>

flaskr/templates/login.html
{% extends "layout.html" %}
{% block body %}
<h2>Login</h2>
{% if error %}
<p class="error">
  <strong>Error: </strong>
  {{ error }}
</p>
{% endif %}
<form action="{{ url_for('login') }}" method="post">
  <dl>
    <dt>Username:</dt>
    <dd><input type="text" name="username" /></dd>
    <dt>Password:</dt>
    <dd><input type="password" name="password" /></dd>
    <dd><input type="submit" value="Login" /></dd>
  </dl>
</form>
{% endblock %}

flaskr/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
{% if current_user.is_authenticated() %}
<form action="{{ url_for('entries.add') }}" method="post" class="add-entry">
  <dl>
    <dt>Title:</dt>
    <dd><input type="text" size="30" name="title" /></dd>
    <dt>Text:</dt>
    <dd><textarea name="text" rows="5" cols="40"></textarea></dd>
    <dd><input type="submit" value="Share" /></dd>
  </dl>
</form>
{% endif %}
<ul class="entries">
  {% for entry in entries %}
  <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}</li>
  {% else %}
  <li><em>Unbelievable. No entries so far</em></li>
  {% endfor %}
</ul>
{% endblock %}